import type { Source } from "../types";

export const NEWS_SOURCES: readonly Source[] = [
  // KR
  {
    id: "yonhap_kr",
    regionId: "kr",
    name: "연합뉴스",
    nameEn: "Yonhap",
    url: "https://www.yna.co.kr",
    type: "news",
    scrapeUrl: "https://www.yna.co.kr/rss/news.xml",
    scrapeIntervalMinutes: 30,
    feedKind: "rss",
    newsCategory: "wire_service",
    trustTier: 1,
    language: "ko",
    isActive: true,
  },
  {
    id: "naver_news_ranking",
    regionId: "kr",
    name: "네이버 뉴스 랭킹",
    nameEn: "Naver News Ranking",
    url: "https://news.naver.com",
    type: "news",
    scrapeUrl: "https://news.naver.com/main/ranking/popularDay.naver",
    scrapeIntervalMinutes: 30,
    feedKind: "html_ranking",
    newsCategory: "portal",
    trustTier: 2,
    language: "ko",
    rankingHint: "popularDay",
    isActive: false, // policy: disable-now (robots disallow)
  },
  {
    id: "daum_news_ranking",
    regionId: "kr",
    name: "다음 뉴스 랭킹",
    nameEn: "Daum News Ranking",
    url: "https://news.daum.net",
    type: "news",
    scrapeUrl: "https://news.daum.net/",
    scrapeIntervalMinutes: 30,
    feedKind: "html_ranking",
    newsCategory: "portal",
    trustTier: 2,
    language: "ko",
    rankingHint: "ranking/popular",
    isActive: true,
  },
  {
    id: "chosun_rss",
    regionId: "kr",
    name: "조선일보 RSS",
    nameEn: "Chosun RSS",
    url: "https://www.chosun.com",
    type: "news",
    scrapeUrl: "https://www.chosun.com/arc/outboundfeeds/rss/?outputType=xml",
    scrapeIntervalMinutes: 60,
    feedKind: "rss",
    newsCategory: "newspaper",
    trustTier: 2,
    language: "ko",
    isActive: true,
  },
  {
    id: "joongang_rss",
    regionId: "kr",
    name: "중앙일보 RSS",
    nameEn: "JoongAng RSS",
    url: "https://www.joongang.co.kr",
    type: "news",
    scrapeUrl: "https://rss.joins.com/joins_homenews_list.xml",
    scrapeIntervalMinutes: 60,
    feedKind: "rss",
    newsCategory: "newspaper",
    trustTier: 2,
    language: "ko",
    isActive: false, // policy: disable-until-fixed (empty feed)
  },
  {
    id: "hankyoreh_rss",
    regionId: "kr",
    name: "한겨레 RSS",
    nameEn: "Hankyoreh RSS",
    url: "https://www.hani.co.kr",
    type: "news",
    scrapeUrl: "https://www.hani.co.kr/rss/",
    scrapeIntervalMinutes: 60,
    feedKind: "rss",
    newsCategory: "newspaper",
    trustTier: 2,
    language: "ko",
    isActive: true,
  },
  {
    id: "kbs_news_rss",
    regionId: "kr",
    name: "KBS 뉴스 RSS",
    nameEn: "KBS News RSS",
    url: "https://news.kbs.co.kr",
    type: "news",
    scrapeUrl: "https://news.kbs.co.kr/news/pc/main/main.html",
    scrapeIntervalMinutes: 60,
    feedKind: "html_ranking",
    newsCategory: "broadcaster",
    trustTier: 2,
    language: "ko",
    isActive: true,
  },
  {
    id: "ytn_rss",
    regionId: "kr",
    name: "YTN RSS",
    nameEn: "YTN RSS",
    url: "https://www.ytn.co.kr",
    type: "news",
    scrapeUrl: "https://www.ytn.co.kr/",
    scrapeIntervalMinutes: 60,
    feedKind: "html_ranking",
    newsCategory: "broadcaster",
    trustTier: 2,
    language: "ko",
    isActive: true,
  },

  // JP
  {
    id: "kyodo_rss",
    regionId: "jp",
    name: "共同通信 RSS",
    nameEn: "Kyodo RSS",
    url: "https://english.kyodonews.net",
    type: "news",
    scrapeUrl: "https://english.kyodonews.net/",
    scrapeIntervalMinutes: 30,
    feedKind: "html_ranking",
    newsCategory: "wire_service",
    trustTier: 1,
    language: "ja",
    isActive: true,
  },
  {
    id: "yahoo_japan_news_ranking",
    regionId: "jp",
    name: "Yahoo! Japan 뉴스 랭킹",
    nameEn: "Yahoo! Japan News Ranking",
    url: "https://news.yahoo.co.jp",
    type: "news",
    scrapeUrl: "https://news.yahoo.co.jp/ranking/access/news",
    scrapeIntervalMinutes: 30,
    feedKind: "html_ranking",
    newsCategory: "portal",
    trustTier: 2,
    language: "ja",
    isActive: true,
  },
  {
    id: "nhk_rss",
    regionId: "jp",
    name: "NHK RSS",
    nameEn: "NHK RSS",
    url: "https://www3.nhk.or.jp",
    type: "news",
    scrapeUrl: "https://www3.nhk.or.jp/rss/news/cat0.xml",
    scrapeIntervalMinutes: 60,
    feedKind: "rss",
    newsCategory: "broadcaster",
    trustTier: 2,
    language: "ja",
    isActive: true,
  },
  {
    id: "asahi_rss",
    regionId: "jp",
    name: "朝日新聞 RSS",
    nameEn: "Asahi RSS",
    url: "https://www.asahi.com",
    type: "news",
    scrapeUrl: "https://www.asahi.com/rss/asahi/newsheadlines.rdf",
    scrapeIntervalMinutes: 60,
    feedKind: "rss",
    newsCategory: "newspaper",
    trustTier: 2,
    language: "ja",
    isActive: true,
  },
  {
    id: "yomiuri_rss",
    regionId: "jp",
    name: "読売新聞 RSS",
    nameEn: "Yomiuri RSS",
    url: "https://www.yomiuri.co.jp",
    type: "news",
    scrapeUrl: "https://www.yomiuri.co.jp/",
    scrapeIntervalMinutes: 60,
    feedKind: "html_ranking",
    newsCategory: "newspaper",
    trustTier: 2,
    language: "ja",
    isActive: true,
  },
  {
    id: "mainichi_rss",
    regionId: "jp",
    name: "毎日新聞 RSS",
    nameEn: "Mainichi RSS",
    url: "https://mainichi.jp",
    type: "news",
    scrapeUrl: "https://mainichi.jp/rss/etc/mainichi-flash.rss",
    scrapeIntervalMinutes: 60,
    feedKind: "rss",
    newsCategory: "newspaper",
    trustTier: 2,
    language: "ja",
    isActive: true,
  },
  {
    id: "nikkei_rss",
    regionId: "jp",
    name: "日経 RSS",
    nameEn: "Nikkei RSS",
    url: "https://www.nikkei.com",
    type: "news",
    scrapeUrl: "https://www.nikkei.com/rss/",
    scrapeIntervalMinutes: 60,
    feedKind: "rss",
    newsCategory: "business_media",
    trustTier: 2,
    language: "ja",
    isActive: false, // TODO: paywall-heavy sections, verify free feeds only.
  },

  // US
  {
    id: "ap_rss",
    regionId: "us",
    name: "AP News RSS",
    nameEn: "AP News RSS",
    url: "https://apnews.com",
    type: "news",
    scrapeUrl: "https://apnews.com/",
    scrapeIntervalMinutes: 30,
    feedKind: "html_ranking",
    newsCategory: "wire_service",
    trustTier: 1,
    language: "en",
    isActive: true,
  },
  {
    id: "reuters_rss",
    regionId: "us",
    name: "Reuters RSS",
    nameEn: "Reuters RSS",
    url: "https://www.reuters.com",
    type: "news",
    scrapeUrl: "https://www.reutersagency.com/feed/?best-topics=business-finance&post_type=best",
    scrapeIntervalMinutes: 30,
    feedKind: "rss",
    newsCategory: "wire_service",
    trustTier: 1,
    language: "en",
    isActive: false, // policy: disable-until-fixed (endpoint 404)
  },
  {
    id: "npr_rss",
    regionId: "us",
    name: "NPR RSS",
    nameEn: "NPR RSS",
    url: "https://www.npr.org",
    type: "news",
    scrapeUrl: "https://feeds.npr.org/1001/rss.xml",
    scrapeIntervalMinutes: 60,
    feedKind: "rss",
    newsCategory: "broadcaster",
    trustTier: 2,
    language: "en",
    isActive: true,
  },
  {
    id: "cnn_rss",
    regionId: "us",
    name: "CNN RSS",
    nameEn: "CNN RSS",
    url: "https://edition.cnn.com",
    type: "news",
    scrapeUrl: "http://rss.cnn.com/rss/edition.rss",
    scrapeIntervalMinutes: 60,
    feedKind: "rss",
    newsCategory: "broadcaster",
    trustTier: 2,
    language: "en",
    isActive: true,
  },
  {
    id: "nytimes_rss",
    regionId: "us",
    name: "NYTimes RSS",
    nameEn: "NYTimes RSS",
    url: "https://www.nytimes.com",
    type: "news",
    scrapeUrl: "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml",
    scrapeIntervalMinutes: 60,
    feedKind: "rss",
    newsCategory: "newspaper",
    trustTier: 2,
    language: "en",
    isActive: false, // TODO: keep free/open feed sections only.
  },
  {
    id: "wapo_rss",
    regionId: "us",
    name: "Washington Post RSS",
    nameEn: "Washington Post RSS",
    url: "https://www.washingtonpost.com",
    type: "news",
    scrapeUrl: "https://feeds.washingtonpost.com/rss/world",
    scrapeIntervalMinutes: 60,
    feedKind: "rss",
    newsCategory: "newspaper",
    trustTier: 2,
    language: "en",
    isActive: false, // TODO: paywall-heavy coverage.
  },
  {
    id: "bloomberg_rss",
    regionId: "us",
    name: "Bloomberg RSS",
    nameEn: "Bloomberg RSS",
    url: "https://www.bloomberg.com",
    type: "news",
    scrapeUrl: "https://feeds.bloomberg.com/markets/news.rss",
    scrapeIntervalMinutes: 60,
    feedKind: "rss",
    newsCategory: "business_media",
    trustTier: 2,
    language: "en",
    isActive: false, // TODO: verify freely accessible sections only.
  },
  {
    id: "techcrunch_rss",
    regionId: "us",
    name: "TechCrunch RSS",
    nameEn: "TechCrunch RSS",
    url: "https://techcrunch.com",
    type: "news",
    scrapeUrl: "https://techcrunch.com/feed/",
    scrapeIntervalMinutes: 60,
    feedKind: "rss",
    newsCategory: "tech_media",
    trustTier: 3,
    language: "en",
    isActive: true,
  },

  // EU (including UK feeds mapped into eu region)
  {
    id: "bbc_rss",
    regionId: "eu",
    name: "BBC RSS",
    nameEn: "BBC RSS",
    url: "https://www.bbc.com",
    type: "news",
    scrapeUrl: "https://feeds.bbci.co.uk/news/rss.xml",
    scrapeIntervalMinutes: 60,
    feedKind: "rss",
    newsCategory: "broadcaster",
    trustTier: 2,
    language: "en",
    isActive: true,
  },
  {
    id: "guardian_rss",
    regionId: "eu",
    name: "The Guardian RSS",
    nameEn: "The Guardian RSS",
    url: "https://www.theguardian.com",
    type: "news",
    scrapeUrl: "https://www.theguardian.com/world/rss",
    scrapeIntervalMinutes: 60,
    feedKind: "rss",
    newsCategory: "newspaper",
    trustTier: 2,
    language: "en",
    isActive: true,
  },
  {
    id: "reuters_uk_rss",
    regionId: "eu",
    name: "Reuters UK RSS",
    nameEn: "Reuters UK RSS",
    url: "https://www.reuters.com",
    type: "news",
    scrapeUrl: "https://www.reutersagency.com/feed/?best-regions=europe&post_type=best",
    scrapeIntervalMinutes: 30,
    feedKind: "rss",
    newsCategory: "wire_service",
    trustTier: 1,
    language: "en",
    isActive: false, // policy: disable-until-fixed (endpoint 404)
  },
  {
    id: "euronews_rss",
    regionId: "eu",
    name: "Euronews RSS",
    nameEn: "Euronews RSS",
    url: "https://www.euronews.com",
    type: "news",
    scrapeUrl: "https://www.euronews.com/rss?level=theme&name=news",
    scrapeIntervalMinutes: 60,
    feedKind: "rss",
    newsCategory: "broadcaster",
    trustTier: 2,
    language: "en",
    isActive: true,
  },
  {
    id: "dw_rss",
    regionId: "eu",
    name: "DW RSS",
    nameEn: "DW RSS",
    url: "https://www.dw.com",
    type: "news",
    scrapeUrl: "https://rss.dw.com/xml/rss-en-all",
    scrapeIntervalMinutes: 60,
    feedKind: "rss",
    newsCategory: "broadcaster",
    trustTier: 2,
    language: "en",
    isActive: true,
  },
  {
    id: "lemonde_rss",
    regionId: "eu",
    name: "Le Monde RSS",
    nameEn: "Le Monde RSS",
    url: "https://www.lemonde.fr",
    type: "news",
    scrapeUrl: "https://www.lemonde.fr/rss/une.xml",
    scrapeIntervalMinutes: 60,
    feedKind: "rss",
    newsCategory: "newspaper",
    trustTier: 2,
    language: "fr",
    isActive: true,
  },
  {
    id: "spiegel_rss",
    regionId: "eu",
    name: "Der Spiegel RSS",
    nameEn: "Der Spiegel RSS",
    url: "https://www.spiegel.de",
    type: "news",
    scrapeUrl: "https://www.spiegel.de/schlagzeilen/tops/index.rss",
    scrapeIntervalMinutes: 60,
    feedKind: "rss",
    newsCategory: "newspaper",
    trustTier: 2,
    language: "de",
    isActive: true,
  },
  {
    id: "elpais_rss",
    regionId: "eu",
    name: "El Pais RSS",
    nameEn: "El Pais RSS",
    url: "https://elpais.com",
    type: "news",
    scrapeUrl: "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada",
    scrapeIntervalMinutes: 60,
    feedKind: "rss",
    newsCategory: "newspaper",
    trustTier: 2,
    language: "es",
    isActive: true,
  },

  // CN
  {
    id: "xinhua_rss",
    regionId: "cn",
    name: "Xinhua RSS",
    nameEn: "Xinhua RSS",
    url: "https://www.news.cn",
    type: "news",
    scrapeUrl: "https://www.xinhuanet.com/english/rss/worldrss.xml",
    scrapeIntervalMinutes: 30,
    feedKind: "rss",
    newsCategory: "wire_service",
    trustTier: 1,
    language: "zh",
    isActive: true,
  },
  {
    id: "sina_news_ranking",
    regionId: "cn",
    name: "Sina News Ranking",
    nameEn: "Sina News Ranking",
    url: "https://news.sina.com.cn",
    type: "news",
    scrapeUrl: "https://news.sina.com.cn/hotnews/",
    scrapeIntervalMinutes: 30,
    feedKind: "html_ranking",
    newsCategory: "portal",
    trustTier: 2,
    language: "zh",
    isActive: false, // TODO: selector stability and anti-bot variance.
  },
  {
    id: "sohu_news_ranking",
    regionId: "cn",
    name: "Sohu News Ranking",
    nameEn: "Sohu News Ranking",
    url: "https://news.sohu.com",
    type: "news",
    scrapeUrl: "https://news.sohu.com",
    scrapeIntervalMinutes: 30,
    feedKind: "html_ranking",
    newsCategory: "portal",
    trustTier: 2,
    language: "zh",
    isActive: false, // TODO: selector stability and anti-bot variance.
  },
  {
    id: "163_news_ranking",
    regionId: "cn",
    name: "163 News Ranking",
    nameEn: "163 News Ranking",
    url: "https://news.163.com",
    type: "news",
    scrapeUrl: "https://news.163.com/rank/",
    scrapeIntervalMinutes: 30,
    feedKind: "html_ranking",
    newsCategory: "portal",
    trustTier: 2,
    language: "zh",
    isActive: false, // TODO: selector stability and anti-bot variance.
  },

  // TW
  {
    id: "cna_rss",
    regionId: "tw",
    name: "CNA RSS",
    nameEn: "CNA RSS",
    url: "https://www.cna.com.tw",
    type: "news",
    scrapeUrl: "https://www.cna.com.tw/",
    scrapeIntervalMinutes: 30,
    feedKind: "html_ranking",
    newsCategory: "wire_service",
    trustTier: 1,
    language: "zh",
    isActive: true,
  },
  {
    id: "udn_rss",
    regionId: "tw",
    name: "UDN RSS",
    nameEn: "UDN RSS",
    url: "https://udn.com",
    type: "news",
    scrapeUrl: "https://udn.com/news/index",
    scrapeIntervalMinutes: 60,
    feedKind: "html_ranking",
    newsCategory: "newspaper",
    trustTier: 2,
    language: "zh",
    isActive: true,
  },
  {
    id: "ltn_rss",
    regionId: "tw",
    name: "自由時報 RSS",
    nameEn: "Liberty Times RSS",
    url: "https://news.ltn.com.tw",
    type: "news",
    scrapeUrl: "https://news.ltn.com.tw/rss/all.xml",
    scrapeIntervalMinutes: 60,
    feedKind: "rss",
    newsCategory: "newspaper",
    trustTier: 2,
    language: "zh",
    isActive: true,
  },
  {
    id: "yahoo_tw_ranking",
    regionId: "tw",
    name: "Yahoo Taiwan Ranking",
    nameEn: "Yahoo Taiwan Ranking",
    url: "https://tw.news.yahoo.com",
    type: "news",
    scrapeUrl: "https://tw.news.yahoo.com/most-popular",
    scrapeIntervalMinutes: 30,
    feedKind: "html_ranking",
    newsCategory: "portal",
    trustTier: 2,
    language: "zh",
    isActive: true,
  },

  // RU/CIS
  {
    id: "tass_rss",
    regionId: "ru",
    name: "TASS RSS",
    nameEn: "TASS RSS",
    url: "https://tass.com",
    type: "news",
    scrapeUrl: "https://tass.com/rss/v2.xml",
    scrapeIntervalMinutes: 30,
    feedKind: "rss",
    newsCategory: "wire_service",
    trustTier: 1,
    language: "ru",
    isActive: true,
  },
  {
    id: "rt_rss",
    regionId: "ru",
    name: "RT RSS",
    nameEn: "RT RSS",
    url: "https://www.rt.com",
    type: "news",
    scrapeUrl: "https://www.rt.com/rss/news/",
    scrapeIntervalMinutes: 60,
    feedKind: "rss",
    newsCategory: "broadcaster",
    trustTier: 2,
    language: "en",
    isActive: true,
  },
  {
    id: "yandex_news_trending",
    regionId: "ru",
    name: "Yandex News Trending",
    nameEn: "Yandex News Trending",
    url: "https://news.yandex.ru",
    type: "news",
    scrapeUrl: "https://news.yandex.com",
    scrapeIntervalMinutes: 30,
    feedKind: "html_ranking",
    newsCategory: "portal",
    trustTier: 2,
    language: "ru",
    isActive: true, // policy: keep-active-observe (timeout-prone)
  },
  {
    id: "mail_ru_news",
    regionId: "ru",
    name: "Mail.ru News",
    nameEn: "Mail.ru News",
    url: "https://news.mail.ru",
    type: "news",
    scrapeUrl: "https://news.mail.ru/rss/",
    scrapeIntervalMinutes: 60,
    feedKind: "rss",
    newsCategory: "portal",
    trustTier: 2,
    language: "ru",
    isActive: true,
  },
  {
    id: "meduza_rss",
    regionId: "ru",
    name: "Meduza RSS",
    nameEn: "Meduza RSS",
    url: "https://meduza.io",
    type: "news",
    scrapeUrl: "https://meduza.io/rss2/all",
    scrapeIntervalMinutes: 60,
    feedKind: "rss",
    newsCategory: "newspaper",
    trustTier: 3,
    language: "ru",
    isActive: true,
  },

  // ME
  {
    id: "reuters_mideast_rss",
    regionId: "me",
    name: "Reuters Middle East RSS",
    nameEn: "Reuters Middle East RSS",
    url: "https://www.reuters.com",
    type: "news",
    scrapeUrl: "https://www.reutersagency.com/feed/?best-regions=middle-east&post_type=best",
    scrapeIntervalMinutes: 30,
    feedKind: "rss",
    newsCategory: "wire_service",
    trustTier: 1,
    language: "en",
    isActive: false, // policy: disable-until-fixed (endpoint 404)
  },
  {
    id: "aljazeera_rss",
    regionId: "me",
    name: "Al Jazeera RSS",
    nameEn: "Al Jazeera RSS",
    url: "https://www.aljazeera.com",
    type: "news",
    scrapeUrl: "https://www.aljazeera.com/xml/rss/all.xml",
    scrapeIntervalMinutes: 60,
    feedKind: "rss",
    newsCategory: "broadcaster",
    trustTier: 2,
    language: "en",
    isActive: true,
  },
  {
    id: "bbc_arabic_rss",
    regionId: "me",
    name: "BBC Arabic RSS",
    nameEn: "BBC Arabic RSS",
    url: "https://www.bbc.com/arabic",
    type: "news",
    scrapeUrl: "https://feeds.bbci.co.uk/arabic/rss.xml",
    scrapeIntervalMinutes: 60,
    feedKind: "rss",
    newsCategory: "broadcaster",
    trustTier: 2,
    language: "ar",
    isActive: true,
  },

  // BR
  {
    id: "g1_rss",
    regionId: "br",
    name: "G1 RSS",
    nameEn: "G1 RSS",
    url: "https://g1.globo.com",
    type: "news",
    scrapeUrl: "https://g1.globo.com/rss/g1/",
    scrapeIntervalMinutes: 60,
    feedKind: "rss",
    newsCategory: "portal",
    trustTier: 2,
    language: "pt",
    isActive: true,
  },
  {
    id: "uol_rss",
    regionId: "br",
    name: "UOL RSS",
    nameEn: "UOL RSS",
    url: "https://www.uol.com.br",
    type: "news",
    scrapeUrl: "https://rss.uol.com.br/feed/noticias.xml",
    scrapeIntervalMinutes: 60,
    feedKind: "rss",
    newsCategory: "portal",
    trustTier: 2,
    language: "pt",
    isActive: true,
  },
  {
    id: "folha_rss",
    regionId: "br",
    name: "Folha RSS",
    nameEn: "Folha RSS",
    url: "https://www.folha.uol.com.br",
    type: "news",
    scrapeUrl: "https://feeds.folha.uol.com.br/emcimadahora/rss091.xml",
    scrapeIntervalMinutes: 60,
    feedKind: "rss",
    newsCategory: "newspaper",
    trustTier: 2,
    language: "pt",
    isActive: true,
  },

  // IN
  {
    id: "pti_rss",
    regionId: "in",
    name: "PTI RSS",
    nameEn: "PTI RSS",
    url: "https://www.ptinews.com",
    type: "news",
    scrapeUrl: "https://www.ptinews.com/rss/top.xml",
    scrapeIntervalMinutes: 30,
    feedKind: "rss",
    newsCategory: "wire_service",
    trustTier: 1,
    language: "en",
    isActive: false, // TODO: endpoint stability verification.
  },
  {
    id: "thehindu_rss",
    regionId: "in",
    name: "The Hindu RSS",
    nameEn: "The Hindu RSS",
    url: "https://www.thehindu.com",
    type: "news",
    scrapeUrl: "https://www.thehindu.com/news/feeder/default.rss",
    scrapeIntervalMinutes: 60,
    feedKind: "rss",
    newsCategory: "newspaper",
    trustTier: 2,
    language: "en",
    isActive: true,
  },
  {
    id: "ndtv_rss",
    regionId: "in",
    name: "NDTV RSS",
    nameEn: "NDTV RSS",
    url: "https://www.ndtv.com",
    type: "news",
    scrapeUrl: "https://feeds.feedburner.com/ndtvnews-top-stories",
    scrapeIntervalMinutes: 60,
    feedKind: "rss",
    newsCategory: "broadcaster",
    trustTier: 2,
    language: "en",
    isActive: true,
  },
  {
    id: "timesofindia_rss",
    regionId: "in",
    name: "Times of India RSS",
    nameEn: "Times of India RSS",
    url: "https://timesofindia.indiatimes.com",
    type: "news",
    scrapeUrl: "https://timesofindia.indiatimes.com/rssfeedstopstories.cms",
    scrapeIntervalMinutes: 60,
    feedKind: "rss",
    newsCategory: "newspaper",
    trustTier: 2,
    language: "en",
    isActive: true,
  },

  // ID
  {
    id: "antara_rss",
    regionId: "id",
    name: "Antara RSS",
    nameEn: "Antara RSS",
    url: "https://www.antaranews.com",
    type: "news",
    scrapeUrl: "https://www.antaranews.com/rss/terkini",
    scrapeIntervalMinutes: 30,
    feedKind: "rss",
    newsCategory: "wire_service",
    trustTier: 1,
    language: "id",
    isActive: true,
  },
  {
    id: "detik_rss",
    regionId: "id",
    name: "Detik RSS",
    nameEn: "Detik RSS",
    url: "https://news.detik.com",
    type: "news",
    scrapeUrl: "https://news.detik.com/rss",
    scrapeIntervalMinutes: 60,
    feedKind: "rss",
    newsCategory: "portal",
    trustTier: 2,
    language: "id",
    isActive: true,
  },
  {
    id: "kompas_rss",
    regionId: "id",
    name: "Kompas RSS",
    nameEn: "Kompas RSS",
    url: "https://www.kompas.com",
    type: "news",
    scrapeUrl: "https://www.kompas.com/rss",
    scrapeIntervalMinutes: 60,
    feedKind: "rss",
    newsCategory: "newspaper",
    trustTier: 2,
    language: "id",
    isActive: false, // policy: disable-until-fixed (endpoint 404)
  },

  // MX
  {
    id: "eluniversal_rss",
    regionId: "mx",
    name: "El Universal RSS",
    nameEn: "El Universal RSS",
    url: "https://www.eluniversal.com.mx",
    type: "news",
    scrapeUrl: "https://www.eluniversal.com.mx/",
    scrapeIntervalMinutes: 60,
    feedKind: "html_ranking",
    newsCategory: "newspaper",
    trustTier: 2,
    language: "es",
    isActive: true,
  },
  {
    id: "milenio_rss",
    regionId: "mx",
    name: "Milenio RSS",
    nameEn: "Milenio RSS",
    url: "https://www.milenio.com",
    type: "news",
    scrapeUrl: "https://www.milenio.com/",
    scrapeIntervalMinutes: 60,
    feedKind: "html_ranking",
    newsCategory: "newspaper",
    trustTier: 2,
    language: "es",
    isActive: true,
  },

  // AU
  {
    id: "abc_news_rss",
    regionId: "au",
    name: "ABC News RSS",
    nameEn: "ABC News RSS",
    url: "https://www.abc.net.au",
    type: "news",
    scrapeUrl: "https://www.abc.net.au/news/feed/51120/rss.xml",
    scrapeIntervalMinutes: 60,
    feedKind: "rss",
    newsCategory: "broadcaster",
    trustTier: 2,
    language: "en",
    isActive: true,
  },
  {
    id: "smh_rss",
    regionId: "au",
    name: "SMH RSS",
    nameEn: "SMH RSS",
    url: "https://www.smh.com.au",
    type: "news",
    scrapeUrl: "https://www.smh.com.au/rss/feed.xml",
    scrapeIntervalMinutes: 60,
    feedKind: "rss",
    newsCategory: "newspaper",
    trustTier: 2,
    language: "en",
    isActive: false, // policy: disable-now (http 403)
  },

  // VN
  {
    id: "vnexpress_rss",
    regionId: "vn",
    name: "VnExpress RSS",
    nameEn: "VnExpress RSS",
    url: "https://vnexpress.net",
    type: "news",
    scrapeUrl: "https://vnexpress.net/rss/tin-moi-nhat.rss",
    scrapeIntervalMinutes: 60,
    feedKind: "rss",
    newsCategory: "portal",
    trustTier: 2,
    language: "vi",
    isActive: true,
  },
  {
    id: "tuoitre_rss",
    regionId: "vn",
    name: "Tuoi Tre RSS",
    nameEn: "Tuoi Tre RSS",
    url: "https://tuoitre.vn",
    type: "news",
    scrapeUrl: "https://tuoitre.vn/rss/tin-moi-nhat.rss",
    scrapeIntervalMinutes: 60,
    feedKind: "rss",
    newsCategory: "newspaper",
    trustTier: 2,
    language: "vi",
    isActive: true,
  },

  // TH
  {
    id: "bangkokpost_rss",
    regionId: "th",
    name: "Bangkok Post RSS",
    nameEn: "Bangkok Post RSS",
    url: "https://www.bangkokpost.com",
    type: "news",
    scrapeUrl: "https://www.bangkokpost.com/rss/data/topstories.xml",
    scrapeIntervalMinutes: 60,
    feedKind: "rss",
    newsCategory: "newspaper",
    trustTier: 2,
    language: "en",
    isActive: false, // policy: disable-now (http 403)
  },
  {
    id: "thairath_rss",
    regionId: "th",
    name: "Thairath RSS",
    nameEn: "Thairath RSS",
    url: "https://www.thairath.co.th",
    type: "news",
    scrapeUrl: "https://www.thairath.co.th/rss/news",
    scrapeIntervalMinutes: 60,
    feedKind: "rss",
    newsCategory: "newspaper",
    trustTier: 2,
    language: "th",
    isActive: true,
  },

  // AR
  {
    id: "clarin_rss",
    regionId: "ar",
    name: "Clarin RSS",
    nameEn: "Clarin RSS",
    url: "https://www.clarin.com",
    type: "news",
    scrapeUrl: "https://www.clarin.com/rss/lo-ultimo/",
    scrapeIntervalMinutes: 60,
    feedKind: "rss",
    newsCategory: "newspaper",
    trustTier: 2,
    language: "es",
    isActive: true,
  },
  {
    id: "lanacion_rss",
    regionId: "ar",
    name: "La Nacion RSS",
    nameEn: "La Nacion RSS",
    url: "https://www.lanacion.com.ar",
    type: "news",
    scrapeUrl: "https://www.lanacion.com.ar/arc/outboundfeeds/rss/",
    scrapeIntervalMinutes: 60,
    feedKind: "rss",
    newsCategory: "newspaper",
    trustTier: 2,
    language: "es",
    isActive: true,
  },

  // CA
  {
    id: "cbc_rss",
    regionId: "ca",
    name: "CBC RSS",
    nameEn: "CBC RSS",
    url: "https://www.cbc.ca",
    type: "news",
    scrapeUrl: "https://www.cbc.ca/webfeed/rss/rss-topstories",
    scrapeIntervalMinutes: 60,
    feedKind: "rss",
    newsCategory: "broadcaster",
    trustTier: 2,
    language: "en",
    isActive: true,
  },
  {
    id: "globeandmail_rss",
    regionId: "ca",
    name: "Globe and Mail RSS",
    nameEn: "Globe and Mail RSS",
    url: "https://www.theglobeandmail.com",
    type: "news",
    scrapeUrl: "https://www.theglobeandmail.com/",
    scrapeIntervalMinutes: 60,
    feedKind: "html_ranking",
    newsCategory: "newspaper",
    trustTier: 2,
    language: "en",
    isActive: true,
  },

  // NG
  {
    id: "punch_rss",
    regionId: "ng",
    name: "Punch RSS",
    nameEn: "Punch RSS",
    url: "https://punchng.com",
    type: "news",
    scrapeUrl: "https://punchng.com/feed/",
    scrapeIntervalMinutes: 60,
    feedKind: "rss",
    newsCategory: "newspaper",
    trustTier: 2,
    language: "en",
    isActive: false, // policy: disable-now (http 403)
  },
  {
    id: "thisday_rss",
    regionId: "ng",
    name: "ThisDay RSS",
    nameEn: "ThisDay RSS",
    url: "https://www.thisdaylive.com",
    type: "news",
    scrapeUrl: "https://www.thisdaylive.com/index.php/feed/",
    scrapeIntervalMinutes: 60,
    feedKind: "rss",
    newsCategory: "newspaper",
    trustTier: 2,
    language: "en",
    isActive: true,
  },

  // ZA
  {
    id: "news24_rss",
    regionId: "za",
    name: "News24 RSS",
    nameEn: "News24 RSS",
    url: "https://www.news24.com",
    type: "news",
    scrapeUrl: "https://feeds.24.com/articles/news24/TopStories/rss",
    scrapeIntervalMinutes: 60,
    feedKind: "rss",
    newsCategory: "portal",
    trustTier: 2,
    language: "en",
    isActive: true,
  },
  {
    id: "iol_rss",
    regionId: "za",
    name: "IOL RSS",
    nameEn: "IOL RSS",
    url: "https://www.iol.co.za",
    type: "news",
    scrapeUrl: "https://www.iol.co.za/cmlink/1.640",
    scrapeIntervalMinutes: 60,
    feedKind: "rss",
    newsCategory: "newspaper",
    trustTier: 2,
    language: "en",
    isActive: false, // policy: disable-now (http 403)
  },
] as const;
