export const REGIONS = [
  {
    id: "kr",
    nameKo: "한국",
    nameEn: "South Korea",
    flagEmoji: "🇰🇷",
    timezone: "Asia/Seoul",
    color: "#3B82F6",
    sortOrder: 1,
  },
  {
    id: "jp",
    nameKo: "일본",
    nameEn: "Japan",
    flagEmoji: "🇯🇵",
    timezone: "Asia/Tokyo",
    color: "#EF4444",
    sortOrder: 2,
  },
  {
    id: "tw",
    nameKo: "대만",
    nameEn: "Taiwan",
    flagEmoji: "🇹🇼",
    timezone: "Asia/Taipei",
    color: "#10B981",
    sortOrder: 3,
  },
  {
    id: "cn",
    nameKo: "중국",
    nameEn: "China",
    flagEmoji: "🇨🇳",
    timezone: "Asia/Shanghai",
    color: "#F59E0B",
    sortOrder: 4,
  },
  {
    id: "us",
    nameKo: "미국",
    nameEn: "United States",
    flagEmoji: "🇺🇸",
    timezone: "America/New_York",
    color: "#8B5CF6",
    sortOrder: 5,
  },
  {
    id: "eu",
    nameKo: "유럽",
    nameEn: "Europe",
    flagEmoji: "🇪🇺",
    timezone: "Europe/London",
    color: "#06B6D4",
    sortOrder: 6,
  },
  {
    id: "me",
    nameKo: "중동",
    nameEn: "Middle East",
    flagEmoji: "🌍",
    timezone: "Asia/Dubai",
    color: "#D97706",
    sortOrder: 7,
  },
  {
    id: "ru",
    nameKo: "러시아/CIS",
    nameEn: "Russia/CIS",
    flagEmoji: "🇷🇺",
    timezone: "Europe/Moscow",
    color: "#64748B",
    sortOrder: 8,
  },
] as const;

export const SOURCES = [
  {
    id: "dcinside",
    regionId: "kr",
    name: "디시인사이드",
    nameEn: "DCInside",
    url: "https://www.dcinside.com",
    type: "community" as const,
    scrapeUrl: "https://gall.dcinside.com/board/lists?id=hit&page=1",
    scrapeIntervalMinutes: 15,
  },
  {
    id: "fmkorea",
    regionId: "kr",
    name: "FM코리아",
    nameEn: "FMKorea",
    url: "https://www.fmkorea.com",
    type: "community" as const,
    scrapeUrl: "https://www.fmkorea.com/index.php?mid=best",
    scrapeIntervalMinutes: 15,
  },
  {
    id: "clien",
    regionId: "kr",
    name: "클리앙",
    nameEn: "Clien",
    url: "https://www.clien.net",
    type: "community" as const,
    scrapeUrl: "https://www.clien.net/service/board/park",
    scrapeIntervalMinutes: 30,
  },
  {
    id: "ruliweb",
    regionId: "kr",
    name: "루리웹",
    nameEn: "Ruliweb",
    url: "https://bbs.ruliweb.com",
    type: "community" as const,
    scrapeUrl: "https://bbs.ruliweb.com/best/selection",
    scrapeIntervalMinutes: 30,
  },
  {
    id: "theqoo",
    regionId: "kr",
    name: "더쿠",
    nameEn: "TheQoo",
    url: "https://theqoo.net",
    type: "community" as const,
    scrapeUrl: "https://theqoo.net/hot",
    scrapeIntervalMinutes: 15,
  },
  {
    id: "ppomppu",
    regionId: "kr",
    name: "뽐뿌",
    nameEn: "Ppomppu",
    url: "https://www.ppomppu.co.kr",
    type: "community" as const,
    scrapeUrl: "https://www.ppomppu.co.kr/zboard/zboard.php?id=freeboard",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "fivech",
    regionId: "jp",
    name: "5ch",
    nameEn: "5ch (2channel)",
    url: "https://5ch.net",
    type: "community" as const,
    scrapeUrl: "https://5ch.net",
    scrapeIntervalMinutes: 30,
  },
  {
    id: "hatena",
    regionId: "jp",
    name: "はてなブックマーク",
    nameEn: "Hatena Bookmark",
    url: "https://b.hatena.ne.jp",
    type: "community" as const,
    scrapeUrl: "https://b.hatena.ne.jp/hotentry/all",
    scrapeIntervalMinutes: 30,
  },
  {
    id: "ptt",
    regionId: "tw",
    name: "PTT",
    nameEn: "PTT BBS",
    url: "https://www.ptt.cc",
    type: "community" as const,
    scrapeUrl: "https://www.ptt.cc/bbs/Gossiping/index.html",
    scrapeIntervalMinutes: 30,
  },
  {
    id: "dcard",
    regionId: "tw",
    name: "Dcard",
    nameEn: "Dcard",
    url: "https://www.dcard.tw",
    type: "community" as const,
    scrapeUrl: "https://www.dcard.tw/service/api/v2/posts?popular=true&limit=30",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "weibo",
    regionId: "cn",
    name: "微博 핫서치",
    nameEn: "Weibo Hot Search",
    url: "https://weibo.com",
    type: "sns" as const,
    scrapeUrl: "https://weibo.com/ajax/side/hotSearch",
    scrapeIntervalMinutes: 30,
  },
  {
    id: "zhihu",
    regionId: "cn",
    name: "知乎 핫 토픽",
    nameEn: "Zhihu Hot",
    url: "https://www.zhihu.com",
    type: "community" as const,
    scrapeUrl: "https://www.zhihu.com/hot",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "bilibili",
    regionId: "cn",
    name: "Bilibili 트렌딩",
    nameEn: "Bilibili Trending",
    url: "https://www.bilibili.com",
    type: "sns" as const,
    scrapeUrl: "https://api.bilibili.com/x/web-interface/ranking/v2",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "reddit",
    regionId: "us",
    name: "Reddit",
    nameEn: "Reddit",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/all/hot.json?limit=50",
    scrapeIntervalMinutes: 15,
  },
  {
    id: "reddit_worldnews",
    regionId: "us",
    name: "Reddit WorldNews",
    nameEn: "Reddit r/worldnews",
    url: "https://www.reddit.com/r/worldnews",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/worldnews/hot.json?limit=30",
    scrapeIntervalMinutes: 30,
  },
  {
    id: "fourchan",
    regionId: "us",
    name: "4chan",
    nameEn: "4chan",
    url: "https://4chan.org",
    type: "community" as const,
    scrapeUrl: "https://a.4cdn.org/pol/catalog.json",
    scrapeIntervalMinutes: 30,
  },
  {
    id: "hackernews",
    regionId: "us",
    name: "Hacker News",
    nameEn: "Hacker News",
    url: "https://news.ycombinator.com",
    type: "community" as const,
    scrapeUrl: "https://hacker-news.firebaseio.com/v0/topstories.json",
    scrapeIntervalMinutes: 30,
  },
  {
    id: "reddit_europe",
    regionId: "eu",
    name: "Reddit Europe",
    nameEn: "Reddit r/europe",
    url: "https://www.reddit.com/r/europe",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/europe/hot.json?limit=30",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "reddit_mideast",
    regionId: "me",
    name: "Reddit Middle East",
    nameEn: "Reddit r/arabs",
    url: "https://www.reddit.com/r/arabs",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/arabs/hot.json?limit=30",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "youtube_kr",
    regionId: "kr",
    name: "YouTube KR 트렌딩",
    nameEn: "YouTube KR Trending",
    url: "https://www.youtube.com",
    type: "sns" as const,
    scrapeUrl:
      "https://www.googleapis.com/youtube/v3/videos?part=snippet,statistics&chart=mostPopular&regionCode=KR&maxResults=20",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "youtube_jp",
    regionId: "jp",
    name: "YouTube JP 트렌딩",
    nameEn: "YouTube JP Trending",
    url: "https://www.youtube.com",
    type: "sns" as const,
    scrapeUrl:
      "https://www.googleapis.com/youtube/v3/videos?part=snippet,statistics&chart=mostPopular&regionCode=JP&maxResults=20",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "youtube_us",
    regionId: "us",
    name: "YouTube US 트렌딩",
    nameEn: "YouTube US Trending",
    url: "https://www.youtube.com",
    type: "sns" as const,
    scrapeUrl:
      "https://www.googleapis.com/youtube/v3/videos?part=snippet,statistics&chart=mostPopular&regionCode=US&maxResults=20",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "mastodon",
    regionId: "eu",
    name: "Mastodon 트렌딩",
    nameEn: "Mastodon Trending",
    url: "https://mastodon.social",
    type: "sns" as const,
    scrapeUrl: "https://mastodon.social/api/v1/trends/statuses",
    scrapeIntervalMinutes: 120,
  },
] as const;

export type RegionId = (typeof REGIONS)[number]["id"];
export type SourceId = (typeof SOURCES)[number]["id"];
