export const REGIONS = [
  {
    id: "kr",
    nameKo: "한국",
    nameEn: "South Korea",
    flagEmoji: "🇰🇷",
    timezone: "Asia/Seoul",
    color: "#3B82F6",
    sortOrder: 1,
  },
  {
    id: "jp",
    nameKo: "일본",
    nameEn: "Japan",
    flagEmoji: "🇯🇵",
    timezone: "Asia/Tokyo",
    color: "#EF4444",
    sortOrder: 2,
  },
  {
    id: "tw",
    nameKo: "대만",
    nameEn: "Taiwan",
    flagEmoji: "🇹🇼",
    timezone: "Asia/Taipei",
    color: "#10B981",
    sortOrder: 3,
  },
  {
    id: "cn",
    nameKo: "중국",
    nameEn: "China",
    flagEmoji: "🇨🇳",
    timezone: "Asia/Shanghai",
    color: "#F59E0B",
    sortOrder: 4,
  },
  {
    id: "us",
    nameKo: "미국",
    nameEn: "United States",
    flagEmoji: "🇺🇸",
    timezone: "America/New_York",
    color: "#8B5CF6",
    sortOrder: 5,
  },
  {
    id: "eu",
    nameKo: "유럽",
    nameEn: "Europe",
    flagEmoji: "🇪🇺",
    timezone: "Europe/London",
    color: "#06B6D4",
    sortOrder: 6,
  },
  {
    id: "me",
    nameKo: "중동",
    nameEn: "Middle East",
    flagEmoji: "🌍",
    timezone: "Asia/Dubai",
    color: "#D97706",
    sortOrder: 7,
  },
  {
    id: "ru",
    nameKo: "러시아/CIS",
    nameEn: "Russia/CIS",
    flagEmoji: "🇷🇺",
    timezone: "Europe/Moscow",
    color: "#64748B",
    sortOrder: 8,
  },
] as const;

export const SOURCES = [
  {
    id: "dcinside",
    regionId: "kr",
    name: "디시인사이드",
    nameEn: "DCInside",
    url: "https://www.dcinside.com",
    type: "community" as const,
    scrapeUrl: "https://gall.dcinside.com/board/lists?id=hit&page=1",
    scrapeIntervalMinutes: 15,
  },
  {
    id: "fmkorea",
    regionId: "kr",
    name: "FM코리아",
    nameEn: "FMKorea",
    url: "https://www.fmkorea.com",
    type: "community" as const,
    scrapeUrl: "https://www.fmkorea.com/index.php?mid=best",
    scrapeIntervalMinutes: 15,
  },
  {
    id: "clien",
    regionId: "kr",
    name: "클리앙",
    nameEn: "Clien",
    url: "https://www.clien.net",
    type: "community" as const,
    scrapeUrl: "https://www.clien.net/service/board/park",
    scrapeIntervalMinutes: 30,
  },
  {
    id: "ruliweb",
    regionId: "kr",
    name: "루리웹",
    nameEn: "Ruliweb",
    url: "https://bbs.ruliweb.com",
    type: "community" as const,
    scrapeUrl: "https://bbs.ruliweb.com/best/selection",
    scrapeIntervalMinutes: 30,
  },
  {
    id: "theqoo",
    regionId: "kr",
    name: "더쿠",
    nameEn: "TheQoo",
    url: "https://theqoo.net",
    type: "community" as const,
    scrapeUrl: "https://theqoo.net/hot",
    scrapeIntervalMinutes: 15,
  },
  {
    id: "ppomppu",
    regionId: "kr",
    name: "뽐뿌",
    nameEn: "Ppomppu",
    url: "https://www.ppomppu.co.kr",
    type: "community" as const,
    scrapeUrl: "https://www.ppomppu.co.kr/zboard/zboard.php?id=freeboard",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "fivech",
    regionId: "jp",
    name: "5ch",
    nameEn: "5ch (2channel)",
    url: "https://5ch.net",
    type: "community" as const,
    scrapeUrl: "https://itest.5ch.io/subbacks/bbynews.json",
    scrapeIntervalMinutes: 30,
  },
  {
    id: "hatena",
    regionId: "jp",
    name: "はてなブックマーク",
    nameEn: "Hatena Bookmark",
    url: "https://b.hatena.ne.jp",
    type: "community" as const,
    scrapeUrl: "https://b.hatena.ne.jp/hotentry/all.rss",
    scrapeIntervalMinutes: 30,
  },
  {
    id: "reddit_japan",
    regionId: "jp",
    name: "Reddit Japan",
    nameEn: "Reddit r/japan",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/japan/hot.json?limit=30",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "reddit_japan_politics",
    regionId: "jp",
    name: "Reddit Japan Politics",
    nameEn: "Reddit r/japanpolitics",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/japanpolitics/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit_japan_tech",
    regionId: "jp",
    name: "Reddit Japan Tech",
    nameEn: "Reddit r/japantech",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/japantech/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit_japanese",
    regionId: "jp",
    name: "Reddit Japanese",
    nameEn: "Reddit r/japanese",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/japanese/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "ptt",
    regionId: "tw",
    name: "PTT",
    nameEn: "PTT BBS",
    url: "https://www.ptt.cc",
    type: "community" as const,
    scrapeUrl: "https://www.ptt.cc/bbs/Gossiping/index.html",
    scrapeIntervalMinutes: 30,
  },
  {
    id: "dcard",
    regionId: "tw",
    name: "Dcard",
    nameEn: "Dcard",
    url: "https://www.dcard.tw",
    type: "community" as const,
    scrapeUrl: "https://www.dcard.tw/service/api/v2/posts?popular=true&limit=30",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "reddit_taiwan",
    regionId: "tw",
    name: "Reddit Taiwan",
    nameEn: "Reddit r/taiwan",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/taiwan/hot.json?limit=30",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "reddit_taiwanese",
    regionId: "tw",
    name: "Reddit Taiwanese",
    nameEn: "Reddit r/taiwanese",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/taiwanese/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit_hongkong",
    regionId: "tw",
    name: "Reddit Hong Kong",
    nameEn: "Reddit r/hongkong",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/hongkong/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit_taiwan_tech",
    regionId: "tw",
    name: "Reddit Taiwan Tech",
    nameEn: "Reddit r/technology",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/technology/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "weibo",
    regionId: "cn",
    name: "微博 핫서치",
    nameEn: "Weibo Hot Search",
    url: "https://weibo.com",
    type: "sns" as const,
    scrapeUrl: "https://weibo.com/ajax/side/hotSearch",
    scrapeIntervalMinutes: 30,
  },
  {
    id: "zhihu",
    regionId: "cn",
    name: "知乎 핫 토픽",
    nameEn: "Zhihu Hot",
    url: "https://www.zhihu.com",
    type: "community" as const,
    scrapeUrl: "https://www.zhihu.com/hot",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "bilibili",
    regionId: "cn",
    name: "Bilibili 트렌딩",
    nameEn: "Bilibili Trending",
    url: "https://www.bilibili.com",
    type: "sns" as const,
    scrapeUrl: "https://s.search.bilibili.com/main/hotword",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "reddit_china",
    regionId: "cn",
    name: "Reddit China",
    nameEn: "Reddit r/china",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/china/hot.json?limit=30",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "reddit_korea_opentalk",
    regionId: "kr",
    name: "Reddit Korea OpenTalk",
    nameEn: "Reddit r/korean",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/korean/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit_kpop",
    regionId: "kr",
    name: "Reddit K-Pop",
    nameEn: "Reddit r/kpop",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/kpop/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit",
    regionId: "us",
    name: "Reddit",
    nameEn: "Reddit",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/all/hot.json?limit=50",
    scrapeIntervalMinutes: 15,
  },
  {
    id: "reddit_worldnews",
    regionId: "us",
    name: "Reddit WorldNews",
    nameEn: "Reddit r/worldnews",
    url: "https://www.reddit.com/r/worldnews",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/worldnews/hot.json?limit=30",
    scrapeIntervalMinutes: 30,
  },
  {
    id: "reddit_science",
    regionId: "us",
    name: "Reddit Science",
    nameEn: "Reddit r/science",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/science/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit_korea",
    regionId: "kr",
    name: "Reddit Korea",
    nameEn: "Reddit r/korea",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/korea/hot.json?limit=30",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "fourchan",
    regionId: "us",
    name: "4chan",
    nameEn: "4chan",
    url: "https://4chan.org",
    type: "community" as const,
    scrapeUrl: "https://a.4cdn.org/pol/catalog.json",
    scrapeIntervalMinutes: 30,
  },
  {
    id: "hackernews",
    regionId: "us",
    name: "Hacker News",
    nameEn: "Hacker News",
    url: "https://news.ycombinator.com",
    type: "community" as const,
    scrapeUrl: "https://hacker-news.firebaseio.com/v0/topstories.json",
    scrapeIntervalMinutes: 30,
  },
  {
    id: "reddit_europe",
    regionId: "eu",
    name: "Reddit Europe",
    nameEn: "Reddit r/europe",
    url: "https://www.reddit.com/r/europe",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/europe/hot.json?limit=30",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "reddit_eu_union",
    regionId: "eu",
    name: "Reddit EU Union",
    nameEn: "Reddit r/europeanunion",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/europeanunion/hot.json?limit=30",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "reddit_askuk",
    regionId: "eu",
    name: "Reddit AskUK",
    nameEn: "Reddit r/askuk",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/askuk/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit_greek",
    regionId: "eu",
    name: "Reddit Greece",
    nameEn: "Reddit r/greece",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/greece/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit_germany",
    regionId: "eu",
    name: "Reddit Germany",
    nameEn: "Reddit r/germany",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/germany/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit_france",
    regionId: "eu",
    name: "Reddit France",
    nameEn: "Reddit r/france",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/france/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit_unitedkingdom",
    regionId: "eu",
    name: "Reddit UK",
    nameEn: "Reddit r/unitedkingdom",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/unitedkingdom/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit_spain",
    regionId: "eu",
    name: "Reddit Spain",
    nameEn: "Reddit r/spain",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/spain/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit_italy",
    regionId: "eu",
    name: "Reddit Italy",
    nameEn: "Reddit r/italy",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/italy/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit_mideast",
    regionId: "me",
    name: "Reddit Middle East",
    nameEn: "Reddit r/arabs",
    url: "https://www.reddit.com/r/arabs",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/arabs/hot.json?limit=30",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "reddit_mideast_arabic",
    regionId: "me",
    name: "Reddit Arabic",
    nameEn: "Reddit r/arabic",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/arabic/hot.json?limit=30",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "reddit_pakistan",
    regionId: "me",
    name: "Reddit Pakistan",
    nameEn: "Reddit r/pakistan",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/pakistan/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit_israel",
    regionId: "me",
    name: "Reddit Israel",
    nameEn: "Reddit r/israel",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/israel/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit_iran",
    regionId: "me",
    name: "Reddit Iran",
    nameEn: "Reddit r/iran",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/iran/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit_turkey",
    regionId: "me",
    name: "Reddit Turkey",
    nameEn: "Reddit r/turkey",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/turkey/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit_middleeast",
    regionId: "me",
    name: "Reddit Middle East",
    nameEn: "Reddit r/middleeast",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/middleeast/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit_russia",
    regionId: "ru",
    name: "Reddit Russia",
    nameEn: "Reddit r/russia",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/russia/hot.json?limit=30",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "reddit_russian",
    regionId: "ru",
    name: "Reddit Russian",
    nameEn: "Reddit r/russian",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/russian/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit_ukraine",
    regionId: "ru",
    name: "Reddit Ukraine",
    nameEn: "Reddit r/ukraine",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/ukraine/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit_belarus",
    regionId: "ru",
    name: "Reddit Belarus",
    nameEn: "Reddit r/belarus",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/belarus/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit_politics",
    regionId: "us",
    name: "Reddit Politics",
    nameEn: "Reddit r/politics",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/politics/hot.json?limit=30",
    scrapeIntervalMinutes: 30,
  },
  {
    id: "reddit_news",
    regionId: "us",
    name: "Reddit News",
    nameEn: "Reddit r/news",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/news/hot.json?limit=30",
    scrapeIntervalMinutes: 30,
  },
  {
    id: "inven",
    regionId: "kr",
    name: "Inven",
    nameEn: "Inven",
    url: "https://www.inven.co.kr",
    type: "community" as const,
    scrapeUrl: "https://www.inven.co.kr/webzine/news/?site=webzine",
    scrapeIntervalMinutes: 30,
  },
  {
    id: "instiz",
    regionId: "kr",
    name: "Instiz",
    nameEn: "Instiz",
    url: "https://www.instiz.net",
    type: "community" as const,
    scrapeUrl: "https://www.instiz.net/pt",
    scrapeIntervalMinutes: 30,
  },
  {
    id: "arca",
    regionId: "kr",
    name: "Arca Live",
    nameEn: "Arca Live",
    url: "https://arca.live",
    type: "community" as const,
    scrapeUrl: "https://arca.live/hot",
    scrapeIntervalMinutes: 30,
  },
  {
    id: "yahoo_japan",
    regionId: "jp",
    name: "Yahoo! Japan Topics",
    nameEn: "Yahoo! Japan Topics",
    url: "https://news.yahoo.co.jp",
    type: "community" as const,
    scrapeUrl: "https://news.yahoo.co.jp/rss/topics/top-picks.xml",
    scrapeIntervalMinutes: 30,
  },
  {
    id: "girlschannel",
    regionId: "jp",
    name: "Girls Channel",
    nameEn: "Girls Channel",
    url: "https://girlschannel.net",
    type: "community" as const,
    scrapeUrl: "https://girlschannel.net/new/",
    scrapeIntervalMinutes: 30,
  },
  {
    id: "togetter",
    regionId: "jp",
    name: "Togetter",
    nameEn: "Togetter",
    url: "https://togetter.com",
    type: "community" as const,
    scrapeUrl: "https://togetter.com/",
    scrapeIntervalMinutes: 30,
  },
  {
    id: "bahamut",
    regionId: "tw",
    name: "Bahamut",
    nameEn: "Bahamut",
    url: "https://www.gamer.com.tw",
    type: "community" as const,
    scrapeUrl: "https://www.gamer.com.tw/",
    scrapeIntervalMinutes: 30,
  },
  {
    id: "mobile01",
    regionId: "tw",
    name: "Mobile01",
    nameEn: "Mobile01",
    url: "https://www.mobile01.com",
    type: "community" as const,
    scrapeUrl: "https://www.mobile01.com/topiclist.php?f=638",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "tieba",
    regionId: "cn",
    name: "Tieba Hot Topics",
    nameEn: "Tieba Hot Topics",
    url: "https://tieba.baidu.com",
    type: "community" as const,
    scrapeUrl: "https://tieba.baidu.com/hottopic/browse/topicList?res_type=1",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "slashdot",
    regionId: "us",
    name: "Slashdot",
    nameEn: "Slashdot",
    url: "https://slashdot.org",
    type: "community" as const,
    scrapeUrl: "https://rss.slashdot.org/Slashdot/slashdot",
    scrapeIntervalMinutes: 30,
  },
  {
    id: "fark",
    regionId: "us",
    name: "Fark",
    nameEn: "Fark",
    url: "https://www.fark.com",
    type: "community" as const,
    scrapeUrl: "https://www.fark.com/rss/fark.rss",
    scrapeIntervalMinutes: 30,
  },
  {
    id: "resetera",
    regionId: "us",
    name: "ResetEra",
    nameEn: "ResetEra",
    url: "https://www.resetera.com",
    type: "community" as const,
    scrapeUrl: "https://www.resetera.com/forums/gaming-forum.7/index.rss",
    scrapeIntervalMinutes: 30,
  },
  {
    id: "gutefrage",
    regionId: "eu",
    name: "gutefrage.net",
    nameEn: "gutefrage.net",
    url: "https://www.gutefrage.net",
    type: "community" as const,
    scrapeUrl: "https://www.gutefrage.net/",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "mumsnet",
    regionId: "eu",
    name: "Mumsnet",
    nameEn: "Mumsnet",
    url: "https://www.mumsnet.com",
    type: "community" as const,
    scrapeUrl: "https://www.mumsnet.com/talk/feed",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "youtube_kr",
    regionId: "kr",
    name: "YouTube KR Trending",
    nameEn: "YouTube KR Trending",
    url: "https://www.youtube.com",
    type: "sns" as const,
    scrapeUrl:
      "https://www.googleapis.com/youtube/v3/videos?part=snippet,statistics&chart=mostPopular&regionCode=KR&maxResults=20",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "youtube_jp",
    regionId: "jp",
    name: "YouTube JP Trending",
    nameEn: "YouTube JP Trending",
    url: "https://www.youtube.com",
    type: "sns" as const,
    scrapeUrl:
      "https://www.googleapis.com/youtube/v3/videos?part=snippet,statistics&chart=mostPopular&regionCode=JP&maxResults=20",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "youtube_us",
    regionId: "us",
    name: "YouTube US Trending",
    nameEn: "YouTube US Trending",
    url: "https://www.youtube.com",
    type: "sns" as const,
    scrapeUrl:
      "https://www.googleapis.com/youtube/v3/videos?part=snippet,statistics&chart=mostPopular&regionCode=US&maxResults=20",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "mastodon",
    regionId: "eu",
    name: "Mastodon Trending",
    nameEn: "Mastodon Trending",
    url: "https://mastodon.social",
    type: "sns" as const,
    scrapeUrl: "https://mastodon.social/api/v1/trends/statuses",
    scrapeIntervalMinutes: 120,
  },
] as const;

export type RegionId = (typeof REGIONS)[number]["id"];
export type SourceId = (typeof SOURCES)[number]["id"];

// Cost-control policy: keep high-friction sources disabled by default.
// They can still be run explicitly via --source <id> for ad-hoc diagnostics.
export const DISABLED_SOURCE_ID_SET = new Set<string>([]);
