import { NEWS_SOURCES } from "./sources/news-sources";

export const REGIONS = [
  {
    id: "kr",
    nameKo: "한국",
    nameEn: "South Korea",
    flagEmoji: "🇰🇷",
    timezone: "Asia/Seoul",
    color: "#3B82F6",
    sortOrder: 1,
  },
  {
    id: "jp",
    nameKo: "일본",
    nameEn: "Japan",
    flagEmoji: "🇯🇵",
    timezone: "Asia/Tokyo",
    color: "#EF4444",
    sortOrder: 2,
  },
  {
    id: "tw",
    nameKo: "대만",
    nameEn: "Taiwan",
    flagEmoji: "🇹🇼",
    timezone: "Asia/Taipei",
    color: "#10B981",
    sortOrder: 3,
  },
  {
    id: "cn",
    nameKo: "중국",
    nameEn: "China",
    flagEmoji: "🇨🇳",
    timezone: "Asia/Shanghai",
    color: "#F59E0B",
    sortOrder: 4,
  },
  {
    id: "us",
    nameKo: "미국",
    nameEn: "United States",
    flagEmoji: "🇺🇸",
    timezone: "America/New_York",
    color: "#8B5CF6",
    sortOrder: 5,
  },
  {
    id: "eu",
    nameKo: "유럽",
    nameEn: "Europe",
    flagEmoji: "🇪🇺",
    timezone: "Europe/London",
    color: "#06B6D4",
    sortOrder: 6,
  },
  {
    id: "me",
    nameKo: "중동",
    nameEn: "Middle East",
    flagEmoji: "🌍",
    timezone: "Asia/Dubai",
    color: "#D97706",
    sortOrder: 7,
  },
  {
    id: "ru",
    nameKo: "러시아/CIS",
    nameEn: "Russia/CIS",
    flagEmoji: "🇷🇺",
    timezone: "Europe/Moscow",
    color: "#64748B",
    sortOrder: 8,
  },
  {
    id: "br",
    nameKo: "브라질",
    nameEn: "Brazil",
    flagEmoji: "🇧🇷",
    timezone: "America/Sao_Paulo",
    color: "#22C55E",
    sortOrder: 9,
  },
  {
    id: "in",
    nameKo: "인도",
    nameEn: "India",
    flagEmoji: "🇮🇳",
    timezone: "Asia/Kolkata",
    color: "#F97316",
    sortOrder: 10,
  },
  {
    id: "id",
    nameKo: "인도네시아",
    nameEn: "Indonesia",
    flagEmoji: "🇮🇩",
    timezone: "Asia/Jakarta",
    color: "#14B8A6",
    sortOrder: 11,
  },
  {
    id: "mx",
    nameKo: "멕시코",
    nameEn: "Mexico",
    flagEmoji: "🇲🇽",
    timezone: "America/Mexico_City",
    color: "#16A34A",
    sortOrder: 12,
  },
  {
    id: "au",
    nameKo: "호주",
    nameEn: "Australia",
    flagEmoji: "🇦🇺",
    timezone: "Australia/Sydney",
    color: "#0EA5E9",
    sortOrder: 13,
  },
  {
    id: "vn",
    nameKo: "베트남",
    nameEn: "Vietnam",
    flagEmoji: "🇻🇳",
    timezone: "Asia/Ho_Chi_Minh",
    color: "#F43F5E",
    sortOrder: 14,
  },
  {
    id: "th",
    nameKo: "태국",
    nameEn: "Thailand",
    flagEmoji: "🇹🇭",
    timezone: "Asia/Bangkok",
    color: "#EAB308",
    sortOrder: 15,
  },
  {
    id: "ar",
    nameKo: "아르헨티나",
    nameEn: "Argentina",
    flagEmoji: "🇦🇷",
    timezone: "America/Argentina/Buenos_Aires",
    color: "#38BDF8",
    sortOrder: 16,
  },
  {
    id: "ca",
    nameKo: "캐나다",
    nameEn: "Canada",
    flagEmoji: "🇨🇦",
    timezone: "America/Toronto",
    color: "#EF4444",
    sortOrder: 17,
  },
  {
    id: "ng",
    nameKo: "나이지리아",
    nameEn: "Nigeria",
    flagEmoji: "🇳🇬",
    timezone: "Africa/Lagos",
    color: "#84CC16",
    sortOrder: 18,
  },
  {
    id: "za",
    nameKo: "남아프리카공화국",
    nameEn: "South Africa",
    flagEmoji: "🇿🇦",
    timezone: "Africa/Johannesburg",
    color: "#10B981",
    sortOrder: 19,
  },
] as const;

const CORE_SOURCES = [
  // KR
  {
    id: "dcinside",
    regionId: "kr",
    name: "디시인사이드",
    nameEn: "DCInside",
    url: "https://www.dcinside.com",
    type: "community" as const,
    scrapeUrl: "https://gall.dcinside.com/board/lists?id=hit&page=1",
    scrapeIntervalMinutes: 15,
  },
  {
    id: "fmkorea",
    regionId: "kr",
    name: "FM코리아",
    nameEn: "FMKorea",
    url: "https://www.fmkorea.com",
    type: "community" as const,
    scrapeUrl: "https://www.fmkorea.com/index.php?mid=best",
    scrapeIntervalMinutes: 15,
  },
  {
    id: "clien",
    regionId: "kr",
    name: "클리앙",
    nameEn: "Clien",
    url: "https://www.clien.net",
    type: "community" as const,
    scrapeUrl: "https://www.clien.net/service/board/park",
    scrapeIntervalMinutes: 30,
  },
  {
    id: "ruliweb",
    regionId: "kr",
    name: "루리웹",
    nameEn: "Ruliweb",
    url: "https://bbs.ruliweb.com",
    type: "community" as const,
    scrapeUrl: "https://bbs.ruliweb.com/best/selection",
    scrapeIntervalMinutes: 30,
  },
  {
    id: "theqoo",
    regionId: "kr",
    name: "더쿠",
    nameEn: "TheQoo",
    url: "https://theqoo.net",
    type: "community" as const,
    scrapeUrl: "https://theqoo.net/hot",
    scrapeIntervalMinutes: 15,
  },
  {
    id: "ppomppu",
    regionId: "kr",
    name: "뽐뿌",
    nameEn: "Ppomppu",
    url: "https://www.ppomppu.co.kr",
    type: "community" as const,
    scrapeUrl: "https://www.ppomppu.co.kr/zboard/zboard.php?id=freeboard",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "inven",
    regionId: "kr",
    name: "Inven",
    nameEn: "Inven",
    url: "https://www.inven.co.kr",
    type: "community" as const,
    scrapeUrl: "https://www.inven.co.kr/webzine/news/?site=webzine",
    scrapeIntervalMinutes: 30,
  },
  {
    id: "instiz",
    regionId: "kr",
    name: "Instiz",
    nameEn: "Instiz",
    url: "https://www.instiz.net",
    type: "community" as const,
    scrapeUrl: "https://www.instiz.net/pt",
    scrapeIntervalMinutes: 30,
  },
  {
    id: "arca",
    regionId: "kr",
    name: "Arca Live",
    nameEn: "Arca Live",
    url: "https://arca.live",
    type: "community" as const,
    scrapeUrl: "https://arca.live/hot",
    scrapeIntervalMinutes: 30,
  },
  {
    id: "reddit_korea",
    regionId: "kr",
    name: "Reddit Korea",
    nameEn: "Reddit r/korea",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/korea/hot.json?limit=30",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "reddit_korea_opentalk",
    regionId: "kr",
    name: "Reddit Korean",
    nameEn: "Reddit r/korean",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/korean/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit_kpop",
    regionId: "kr",
    name: "Reddit K-Pop",
    nameEn: "Reddit r/kpop",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/kpop/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },

  // JP
  {
    id: "fivech",
    regionId: "jp",
    name: "5ch",
    nameEn: "5ch",
    url: "https://5ch.net",
    type: "community" as const,
    scrapeUrl: "https://itest.5ch.io/subbacks/bbynews.json",
    scrapeIntervalMinutes: 30,
  },
  {
    id: "hatena",
    regionId: "jp",
    name: "はてな",
    nameEn: "Hatena",
    url: "https://b.hatena.ne.jp",
    type: "community" as const,
    scrapeUrl: "https://b.hatena.ne.jp/hotentry/all.rss",
    scrapeIntervalMinutes: 30,
  },
  {
    id: "yahoo_japan",
    regionId: "jp",
    name: "Yahoo! Japan Topics",
    nameEn: "Yahoo! Japan Topics",
    url: "https://news.yahoo.co.jp",
    type: "community" as const,
    scrapeUrl: "https://news.yahoo.co.jp/rss/topics/top-picks.xml",
    scrapeIntervalMinutes: 30,
  },
  {
    id: "girlschannel",
    regionId: "jp",
    name: "Girls Channel",
    nameEn: "Girls Channel",
    url: "https://girlschannel.net",
    type: "community" as const,
    scrapeUrl: "https://girlschannel.net/new/",
    scrapeIntervalMinutes: 30,
  },
  {
    id: "togetter",
    regionId: "jp",
    name: "Togetter",
    nameEn: "Togetter",
    url: "https://togetter.com",
    type: "community" as const,
    scrapeUrl: "https://togetter.com/",
    scrapeIntervalMinutes: 30,
  },
  {
    id: "reddit_japan",
    regionId: "jp",
    name: "Reddit Japan",
    nameEn: "Reddit r/japan",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/japan/hot.json?limit=30",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "reddit_japan_politics",
    regionId: "jp",
    name: "Reddit Japan Politics",
    nameEn: "Reddit r/japanpolitics",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/japanpolitics/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit_japan_tech",
    regionId: "jp",
    name: "Reddit Japan Tech",
    nameEn: "Reddit r/japantech",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/japantech/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit_japanese",
    regionId: "jp",
    name: "Reddit Japanese",
    nameEn: "Reddit r/japanese",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/japanese/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },

  // TW
  {
    id: "ptt",
    regionId: "tw",
    name: "PTT",
    nameEn: "PTT",
    url: "https://www.ptt.cc",
    type: "community" as const,
    scrapeUrl: "https://www.ptt.cc/bbs/Gossiping/index.html",
    scrapeIntervalMinutes: 30,
  },
  {
    id: "dcard",
    regionId: "tw",
    name: "Dcard",
    nameEn: "Dcard",
    url: "https://www.dcard.tw",
    type: "community" as const,
    scrapeUrl: "https://www.dcard.tw/service/api/v2/posts?popular=true&limit=30",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "bahamut",
    regionId: "tw",
    name: "Bahamut",
    nameEn: "Bahamut",
    url: "https://www.gamer.com.tw",
    type: "community" as const,
    scrapeUrl: "https://www.gamer.com.tw/",
    scrapeIntervalMinutes: 30,
  },
  {
    id: "mobile01",
    regionId: "tw",
    name: "Mobile01",
    nameEn: "Mobile01",
    url: "https://www.mobile01.com",
    type: "community" as const,
    scrapeUrl: "https://www.mobile01.com/topiclist.php?f=638",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "reddit_taiwan",
    regionId: "tw",
    name: "Reddit Taiwan",
    nameEn: "Reddit r/taiwan",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/taiwan/hot.json?limit=30",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "reddit_taiwanese",
    regionId: "tw",
    name: "Reddit Taiwanese",
    nameEn: "Reddit r/taiwanese",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/taiwanese/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit_taiwan_tech",
    regionId: "tw",
    name: "Reddit Taiwan Tech",
    nameEn: "Reddit r/technology",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/technology/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit_hongkong",
    regionId: "cn",
    name: "Reddit Hong Kong",
    nameEn: "Reddit r/hongkong",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/hongkong/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },

  // CN
  {
    id: "weibo",
    regionId: "cn",
    name: "Weibo Hot Search",
    nameEn: "Weibo Hot Search",
    url: "https://weibo.com",
    type: "sns" as const,
    scrapeUrl: "https://weibo.com/ajax/side/hotSearch",
    scrapeIntervalMinutes: 30,
  },
  {
    id: "zhihu",
    regionId: "cn",
    name: "Zhihu Hot",
    nameEn: "Zhihu Hot",
    url: "https://www.zhihu.com",
    type: "community" as const,
    scrapeUrl: "https://www.zhihu.com/hot",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "tieba",
    regionId: "cn",
    name: "Tieba Hot Topics",
    nameEn: "Tieba Hot Topics",
    url: "https://tieba.baidu.com",
    type: "community" as const,
    scrapeUrl: "https://tieba.baidu.com/hottopic/browse/topicList?res_type=1",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "bilibili",
    regionId: "cn",
    name: "Bilibili Trending",
    nameEn: "Bilibili Trending",
    url: "https://www.bilibili.com",
    type: "sns" as const,
    scrapeUrl: "https://s.search.bilibili.com/main/hotword",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "reddit_china",
    regionId: "cn",
    name: "Reddit China",
    nameEn: "Reddit r/china",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/china/hot.json?limit=30",
    scrapeIntervalMinutes: 60,
  },

  // US
  {
    id: "reddit",
    regionId: "us",
    name: "Reddit",
    nameEn: "Reddit",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/all/hot.json?limit=50",
    scrapeIntervalMinutes: 15,
  },
  {
    id: "reddit_worldnews",
    regionId: "us",
    name: "Reddit WorldNews",
    nameEn: "Reddit r/worldnews",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/worldnews/hot.json?limit=30",
    scrapeIntervalMinutes: 30,
  },
  {
    id: "reddit_science",
    regionId: "us",
    name: "Reddit Science",
    nameEn: "Reddit r/science",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/science/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit_news",
    regionId: "us",
    name: "Reddit News",
    nameEn: "Reddit r/news",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/news/hot.json?limit=30",
    scrapeIntervalMinutes: 30,
  },
  {
    id: "reddit_politics",
    regionId: "us",
    name: "Reddit Politics",
    nameEn: "Reddit r/politics",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/politics/hot.json?limit=30",
    scrapeIntervalMinutes: 30,
  },
  {
    id: "fourchan",
    regionId: "us",
    name: "4chan",
    nameEn: "4chan",
    url: "https://4chan.org",
    type: "community" as const,
    scrapeUrl: "https://a.4cdn.org/pol/catalog.json",
    scrapeIntervalMinutes: 30,
  },
  {
    id: "hackernews",
    regionId: "us",
    name: "Hacker News",
    nameEn: "Hacker News",
    url: "https://news.ycombinator.com",
    type: "community" as const,
    scrapeUrl: "https://hacker-news.firebaseio.com/v0/topstories.json",
    scrapeIntervalMinutes: 30,
  },
  {
    id: "slashdot",
    regionId: "us",
    name: "Slashdot",
    nameEn: "Slashdot",
    url: "https://slashdot.org",
    type: "community" as const,
    scrapeUrl: "https://rss.slashdot.org/Slashdot/slashdot",
    scrapeIntervalMinutes: 30,
  },
  {
    id: "fark",
    regionId: "us",
    name: "Fark",
    nameEn: "Fark",
    url: "https://www.fark.com",
    type: "community" as const,
    scrapeUrl: "https://www.fark.com/rss/fark.rss",
    scrapeIntervalMinutes: 30,
  },
  {
    id: "resetera",
    regionId: "us",
    name: "ResetEra",
    nameEn: "ResetEra",
    url: "https://www.resetera.com",
    type: "community" as const,
    scrapeUrl: "https://www.resetera.com/forums/gaming-forum.7/index.rss",
    scrapeIntervalMinutes: 30,
  },
  {
    id: "metafilter_rss",
    regionId: "us",
    name: "MetaFilter",
    nameEn: "MetaFilter",
    url: "https://www.metafilter.com",
    type: "community" as const,
    scrapeUrl: "https://rss.metafilter.com/metafilter.rss",
    scrapeIntervalMinutes: 60,
    isActive: true,
  },
  {
    id: "lobsters_rss",
    regionId: "us",
    name: "Lobsters",
    nameEn: "Lobsters",
    url: "https://lobste.rs",
    type: "community" as const,
    scrapeUrl: "https://lobste.rs/rss",
    scrapeIntervalMinutes: 60,
    isActive: true,
  },
  {
    id: "neogaf_gaming_rss",
    regionId: "us",
    name: "NeoGAF Gaming",
    nameEn: "NeoGAF Gaming Discussion",
    url: "https://www.neogaf.com",
    type: "community" as const,
    scrapeUrl: "https://www.neogaf.com/forums/gaming-discussion.2/index.rss",
    scrapeIntervalMinutes: 60,
    isActive: true,
  },

  // EU
  {
    id: "reddit_europe",
    regionId: "eu",
    name: "Reddit Europe",
    nameEn: "Reddit r/europe",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/europe/hot.json?limit=30",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "gutefrage",
    regionId: "eu",
    name: "gutefrage.net",
    nameEn: "gutefrage.net",
    url: "https://www.gutefrage.net",
    type: "community" as const,
    scrapeUrl: "https://www.gutefrage.net/",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "mumsnet",
    regionId: "eu",
    name: "Mumsnet",
    nameEn: "Mumsnet",
    url: "https://www.mumsnet.com",
    type: "community" as const,
    scrapeUrl: "https://www.mumsnet.com/talk/feed",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "hardware_fr_rss",
    regionId: "eu",
    name: "Forum HardWare.fr",
    nameEn: "Forum HardWare.fr",
    url: "https://forum.hardware.fr",
    type: "community" as const,
    scrapeUrl: "https://forum.hardware.fr/rss.php?config=hfr.inc&cat=13&subcat=0&num=10",
    scrapeIntervalMinutes: 60,
    isActive: true,
  },
  {
    id: "reddit_askuk",
    regionId: "eu",
    name: "Reddit AskUK",
    nameEn: "Reddit r/askuk",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/askuk/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit_greek",
    regionId: "eu",
    name: "Reddit Greece",
    nameEn: "Reddit r/greece",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/greece/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit_germany",
    regionId: "eu",
    name: "Reddit Germany",
    nameEn: "Reddit r/germany",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/germany/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit_france",
    regionId: "eu",
    name: "Reddit France",
    nameEn: "Reddit r/france",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/france/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit_unitedkingdom",
    regionId: "eu",
    name: "Reddit UK",
    nameEn: "Reddit r/unitedkingdom",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/unitedkingdom/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit_spain",
    regionId: "eu",
    name: "Reddit Spain",
    nameEn: "Reddit r/spain",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/spain/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit_italy",
    regionId: "eu",
    name: "Reddit Italy",
    nameEn: "Reddit r/italy",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/italy/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },

  // ME / RU
  {
    id: "reddit_mideast",
    regionId: "me",
    name: "Reddit Middle East",
    nameEn: "Reddit r/arabs",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/arabs/hot.json?limit=30",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "reddit_mideast_arabic",
    regionId: "me",
    name: "Reddit Arabic",
    nameEn: "Reddit r/arabic",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/arabic/hot.json?limit=30",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "reddit_pakistan",
    regionId: "me",
    name: "Reddit Pakistan",
    nameEn: "Reddit r/pakistan",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/pakistan/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit_israel",
    regionId: "me",
    name: "Reddit Israel",
    nameEn: "Reddit r/israel",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/israel/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit_iran",
    regionId: "me",
    name: "Reddit Iran",
    nameEn: "Reddit r/iran",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/iran/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit_turkey",
    regionId: "me",
    name: "Reddit Turkey",
    nameEn: "Reddit r/turkey",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/turkey/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit_middleeast",
    regionId: "me",
    name: "Reddit Middle East",
    nameEn: "Reddit r/middleeast",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/middleeast/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "expat_mideast",
    regionId: "me",
    name: "Expat Middle East",
    nameEn: "Expat.com Middle East Forum",
    url: "https://www.expat.com",
    type: "community" as const,
    scrapeUrl: "https://www.expat.com/en/forum/middle-east/",
    scrapeIntervalMinutes: 60,
    isActive: true,
  },
  {
    id: "reddit_russia",
    regionId: "ru",
    name: "Reddit Russia",
    nameEn: "Reddit r/russia",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/russia/hot.json?limit=30",
    scrapeIntervalMinutes: 60,
    isActive: false,
  },
  {
    id: "reddit_russian",
    regionId: "ru",
    name: "Reddit Russian",
    nameEn: "Reddit r/russian",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/russian/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit_ukraine",
    regionId: "ru",
    name: "Reddit Ukraine",
    nameEn: "Reddit r/ukraine",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/ukraine/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit_belarus",
    regionId: "ru",
    name: "Reddit Belarus",
    nameEn: "Reddit r/belarus",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/belarus/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "habr",
    regionId: "ru",
    name: "Habr",
    nameEn: "Habr",
    url: "https://habr.com",
    type: "community" as const,
    scrapeUrl: "https://habr.com/ru/rss/news/",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "dtf_rss",
    regionId: "ru",
    name: "DTF",
    nameEn: "DTF",
    url: "https://dtf.ru",
    type: "community" as const,
    scrapeUrl: "https://dtf.ru/rss/all",
    scrapeIntervalMinutes: 60,
    isActive: true,
  },
  {
    id: "vc_ru_rss",
    regionId: "ru",
    name: "vc.ru",
    nameEn: "vc.ru",
    url: "https://vc.ru",
    type: "community" as const,
    scrapeUrl: "https://vc.ru/rss/all",
    scrapeIntervalMinutes: 60,
    isActive: true,
  },
  {
    id: "reddit_brasil",
    regionId: "br",
    name: "Reddit Brasil",
    nameEn: "Reddit r/brasil",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/brasil/hot.json?limit=30",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "reddit_brazil",
    regionId: "br",
    name: "Reddit Brazil",
    nameEn: "Reddit r/brazil",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/brazil/hot.json?limit=30",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "reddit_brasilivre",
    regionId: "br",
    name: "Reddit Brasil Livre",
    nameEn: "Reddit r/brasilivre",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/brasilivre/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit_india",
    regionId: "in",
    name: "Reddit India",
    nameEn: "Reddit r/india",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/india/hot.json?limit=30",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "reddit_indianews",
    regionId: "in",
    name: "Reddit India News",
    nameEn: "Reddit r/indianews",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/indianews/hot.json?limit=30",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "reddit_indiaspeaks",
    regionId: "in",
    name: "Reddit India Speaks",
    nameEn: "Reddit r/IndiaSpeaks",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/IndiaSpeaks/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit_developersindia",
    regionId: "in",
    name: "Reddit Developers India",
    nameEn: "Reddit r/developersIndia",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/developersIndia/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit_indonesia",
    regionId: "id",
    name: "Reddit Indonesia",
    nameEn: "Reddit r/indonesia",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/indonesia/hot.json?limit=30",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "reddit_jakarta",
    regionId: "id",
    name: "Reddit Jakarta",
    nameEn: "Reddit r/jakarta",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/jakarta/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit_bali",
    regionId: "id",
    name: "Reddit Bali",
    nameEn: "Reddit r/bali",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/bali/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit_mexico",
    regionId: "mx",
    name: "Reddit Mexico",
    nameEn: "Reddit r/mexico",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/mexico/hot.json?limit=30",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "reddit_mexicocity",
    regionId: "mx",
    name: "Reddit Mexico City",
    nameEn: "Reddit r/mexicocity",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/mexicocity/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit_australia",
    regionId: "au",
    name: "Reddit Australia",
    nameEn: "Reddit r/australia",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/australia/hot.json?limit=30",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "reddit_sydney",
    regionId: "au",
    name: "Reddit Sydney",
    nameEn: "Reddit r/sydney",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/sydney/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit_vietnam",
    regionId: "vn",
    name: "Reddit Vietnam",
    nameEn: "Reddit r/vietnam",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/vietnam/hot.json?limit=30",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "reddit_vietnamese",
    regionId: "vn",
    name: "Reddit Vietnamese",
    nameEn: "Reddit r/VietNamese",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/VietNamese/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit_thailand",
    regionId: "th",
    name: "Reddit Thailand",
    nameEn: "Reddit r/Thailand",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/Thailand/hot.json?limit=30",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "reddit_bangkok",
    regionId: "th",
    name: "Reddit Bangkok",
    nameEn: "Reddit r/Bangkok",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/Bangkok/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit_argentina",
    regionId: "ar",
    name: "Reddit Argentina",
    nameEn: "Reddit r/argentina",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/argentina/hot.json?limit=30",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "reddit_buenosaires",
    regionId: "ar",
    name: "Reddit Buenos Aires",
    nameEn: "Reddit r/BuenosAires",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/BuenosAires/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit_canada",
    regionId: "ca",
    name: "Reddit Canada",
    nameEn: "Reddit r/canada",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/canada/hot.json?limit=30",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "reddit_ontario",
    regionId: "ca",
    name: "Reddit Ontario",
    nameEn: "Reddit r/ontario",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/ontario/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit_nigeria",
    regionId: "ng",
    name: "Reddit Nigeria",
    nameEn: "Reddit r/Nigeria",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/Nigeria/hot.json?limit=30",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "reddit_lagos",
    regionId: "ng",
    name: "Reddit Lagos",
    nameEn: "Reddit r/Lagos",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/Lagos/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "reddit_southafrica",
    regionId: "za",
    name: "Reddit South Africa",
    nameEn: "Reddit r/southafrica",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/southafrica/hot.json?limit=30",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "reddit_johannesburg",
    regionId: "za",
    name: "Reddit Johannesburg",
    nameEn: "Reddit r/johannesburg",
    url: "https://www.reddit.com",
    type: "community" as const,
    scrapeUrl: "https://www.reddit.com/r/johannesburg/hot.json?limit=30",
    scrapeIntervalMinutes: 120,
  },
  {
    id: "ozbargain_rss",
    regionId: "au",
    name: "OzBargain",
    nameEn: "OzBargain",
    url: "https://www.ozbargain.com.au",
    type: "community" as const,
    scrapeUrl: "https://www.ozbargain.com.au/deals/feed",
    scrapeIntervalMinutes: 60,
    isActive: true,
    language: "en",
    feedKind: "rss",
  },
  {
    id: "redflagdeals_forum_rss",
    regionId: "ca",
    name: "RedFlagDeals Forums",
    nameEn: "RedFlagDeals Forums",
    url: "https://forums.redflagdeals.com",
    type: "community" as const,
    scrapeUrl: "https://forums.redflagdeals.com/feed/forum/9",
    scrapeIntervalMinutes: 60,
    isActive: true,
    language: "en",
    feedKind: "rss",
  },
  {
    id: "nairaland_rss",
    regionId: "ng",
    name: "Nairaland",
    nameEn: "Nairaland",
    url: "https://www.nairaland.com",
    type: "community" as const,
    scrapeUrl: "https://www.nairaland.com/feed",
    scrapeIntervalMinutes: 60,
    isActive: true,
    language: "en",
    feedKind: "rss",
  },
  {
    id: "wilddog_za_rss",
    regionId: "za",
    name: "Wild Dog Adventure Riding",
    nameEn: "Wild Dog Adventure Riding",
    url: "https://wilddog.net.za",
    type: "community" as const,
    scrapeUrl: "https://wilddog.net.za/forums/-/index.rss",
    scrapeIntervalMinutes: 90,
    isActive: true,
    language: "en",
    feedKind: "rss",
  },
  {
    id: "carbonite_za_rss",
    regionId: "za",
    name: "Carbonite",
    nameEn: "Carbonite",
    url: "https://carbonite.co.za",
    type: "community" as const,
    scrapeUrl: "https://carbonite.co.za/index.php?forums/-/index.rss",
    scrapeIntervalMinutes: 90,
    isActive: true,
    language: "en",
    feedKind: "rss",
  },
  {
    id: "pantip_forum_rss",
    regionId: "th",
    name: "Pantip",
    nameEn: "Pantip",
    url: "https://pantip.com",
    type: "community" as const,
    scrapeUrl: "https://pantip.com/forum/feed",
    scrapeIntervalMinutes: 60,
    isActive: false,
    language: "th",
    feedKind: "rss",
  },
  {
    id: "voz_forum_rss",
    regionId: "vn",
    name: "Voz",
    nameEn: "Voz",
    url: "https://voz.vn",
    type: "community" as const,
    scrapeUrl: "https://voz.vn/f/-/index.rss",
    scrapeIntervalMinutes: 60,
    isActive: true,
    language: "vi",
    feedKind: "rss",
  },
  {
    id: "tinhte_rss",
    regionId: "vn",
    name: "Tinhte",
    nameEn: "Tinhte",
    url: "https://tinhte.vn",
    type: "community" as const,
    scrapeUrl: "https://tinhte.vn/rss",
    scrapeIntervalMinutes: 60,
    isActive: true,
    language: "vi",
    feedKind: "rss",
  },
  {
    id: "adrenaline_forum_rss",
    regionId: "br",
    name: "Adrenaline Forum",
    nameEn: "Adrenaline Forum",
    url: "https://forum.adrenaline.com.br",
    type: "community" as const,
    scrapeUrl: "https://forum.adrenaline.com.br/forums/-/index.rss",
    scrapeIntervalMinutes: 90,
    isActive: true,
    language: "pt",
    feedKind: "rss",
  },
  {
    id: "teambhp_forum_rss",
    regionId: "in",
    name: "Team-BHP Forum",
    nameEn: "Team-BHP Forum",
    url: "https://www.team-bhp.com",
    type: "community" as const,
    scrapeUrl: "https://www.team-bhp.com/forum/external.php?type=RSS2",
    scrapeIntervalMinutes: 90,
    isActive: true,
    language: "en",
    feedKind: "rss",
  },
  {
    id: "skyscrapercity_mx_rss",
    regionId: "mx",
    name: "SkyscraperCity Mexico",
    nameEn: "SkyscraperCity Mexico",
    url: "https://www.skyscrapercity.com",
    type: "community" as const,
    scrapeUrl: "https://www.skyscrapercity.com/forums/mexico.345/index.rss",
    scrapeIntervalMinutes: 120,
    isActive: false,
    language: "es",
    feedKind: "rss",
  },
  {
    id: "skyscrapercity_ar_rss",
    regionId: "ar",
    name: "SkyscraperCity Argentina",
    nameEn: "SkyscraperCity Argentina",
    url: "https://www.skyscrapercity.com",
    type: "community" as const,
    scrapeUrl: "https://www.skyscrapercity.com/forums/argentina.363/index.rss",
    scrapeIntervalMinutes: 120,
    isActive: false,
    language: "es",
    feedKind: "rss",
  },
  {
    id: "kaskus_rss",
    regionId: "id",
    name: "Kaskus",
    nameEn: "Kaskus",
    url: "https://www.kaskus.co.id",
    type: "community" as const,
    scrapeUrl: "https://www.kaskus.co.id/rss",
    scrapeIntervalMinutes: 120,
    isActive: false,
    language: "id",
    feedKind: "rss",
  },

  // SNS
  {
    id: "youtube_kr",
    regionId: "kr",
    name: "YouTube KR Trending",
    nameEn: "YouTube KR Trending",
    url: "https://www.youtube.com",
    type: "sns" as const,
    scrapeUrl:
      "https://www.googleapis.com/youtube/v3/videos?part=snippet,statistics&chart=mostPopular&regionCode=KR&maxResults=20",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "youtube_jp",
    regionId: "jp",
    name: "YouTube JP Trending",
    nameEn: "YouTube JP Trending",
    url: "https://www.youtube.com",
    type: "sns" as const,
    scrapeUrl:
      "https://www.googleapis.com/youtube/v3/videos?part=snippet,statistics&chart=mostPopular&regionCode=JP&maxResults=20",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "youtube_us",
    regionId: "us",
    name: "YouTube US Trending",
    nameEn: "YouTube US Trending",
    url: "https://www.youtube.com",
    type: "sns" as const,
    scrapeUrl:
      "https://www.googleapis.com/youtube/v3/videos?part=snippet,statistics&chart=mostPopular&regionCode=US&maxResults=20",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "youtube_me",
    regionId: "me",
    name: "YouTube ME Trending",
    nameEn: "YouTube Middle East Trending",
    url: "https://www.youtube.com",
    type: "sns" as const,
    scrapeUrl:
      "https://www.googleapis.com/youtube/v3/videos?part=snippet,statistics&chart=mostPopular&regionCode=AE&maxResults=20",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "youtube_ru",
    regionId: "ru",
    name: "YouTube RU Trending",
    nameEn: "YouTube Russia Trending",
    url: "https://www.youtube.com",
    type: "sns" as const,
    scrapeUrl:
      "https://www.googleapis.com/youtube/v3/videos?part=snippet,statistics&chart=mostPopular&regionCode=RU&maxResults=20",
    scrapeIntervalMinutes: 60,
  },
  {
    id: "bluesky_kr",
    regionId: "kr",
    name: "Bluesky KR Signals",
    nameEn: "Bluesky KR Signals",
    url: "https://bsky.app",
    type: "sns" as const,
    scrapeUrl: "https://bsky.social/xrpc/app.bsky.feed.getAuthorFeed",
    scrapeIntervalMinutes: 30,
    isActive: false,
  },
  {
    id: "bluesky_jp",
    regionId: "jp",
    name: "Bluesky JP Signals",
    nameEn: "Bluesky JP Signals",
    url: "https://bsky.app",
    type: "sns" as const,
    scrapeUrl: "https://bsky.social/xrpc/app.bsky.feed.getAuthorFeed",
    scrapeIntervalMinutes: 30,
    isActive: false,
  },
  {
    id: "bluesky_tw",
    regionId: "tw",
    name: "Bluesky TW Signals",
    nameEn: "Bluesky TW Signals",
    url: "https://bsky.app",
    type: "sns" as const,
    scrapeUrl: "https://bsky.social/xrpc/app.bsky.feed.getAuthorFeed",
    scrapeIntervalMinutes: 30,
    isActive: false,
  },
  {
    id: "bluesky_cn",
    regionId: "cn",
    name: "Bluesky CN Signals",
    nameEn: "Bluesky CN Signals",
    url: "https://bsky.app",
    type: "sns" as const,
    scrapeUrl: "https://bsky.social/xrpc/app.bsky.feed.getAuthorFeed",
    scrapeIntervalMinutes: 30,
    isActive: false,
  },
  {
    id: "bluesky_us",
    regionId: "us",
    name: "Bluesky US Signals",
    nameEn: "Bluesky US Signals",
    url: "https://bsky.app",
    type: "sns" as const,
    scrapeUrl: "https://bsky.social/xrpc/app.bsky.feed.getAuthorFeed",
    scrapeIntervalMinutes: 30,
    isActive: true,
  },
  {
    id: "bluesky_eu",
    regionId: "eu",
    name: "Bluesky EU Signals",
    nameEn: "Bluesky Europe Signals",
    url: "https://bsky.app",
    type: "sns" as const,
    scrapeUrl: "https://bsky.social/xrpc/app.bsky.feed.getAuthorFeed",
    scrapeIntervalMinutes: 30,
    isActive: true,
  },
  {
    id: "bluesky_me",
    regionId: "me",
    name: "Bluesky ME Signals",
    nameEn: "Bluesky Middle East Signals",
    url: "https://bsky.app",
    type: "sns" as const,
    scrapeUrl: "https://bsky.social/xrpc/app.bsky.feed.getAuthorFeed",
    scrapeIntervalMinutes: 30,
    isActive: false,
  },
  {
    id: "bluesky_ru",
    regionId: "ru",
    name: "Bluesky RU Signals",
    nameEn: "Bluesky Russia Signals",
    url: "https://bsky.app",
    type: "sns" as const,
    scrapeUrl: "https://bsky.social/xrpc/app.bsky.feed.getAuthorFeed",
    scrapeIntervalMinutes: 30,
    isActive: false,
  },
  {
    id: "mastodon_kr",
    regionId: "kr",
    name: "Mastodon KR Signals",
    nameEn: "Mastodon KR Signals",
    url: "https://mastodon.social",
    type: "sns" as const,
    scrapeUrl: "https://mastodon.social/api/v1/timelines/public?local=true",
    scrapeIntervalMinutes: 30,
    isActive: false,
  },
  {
    id: "mastodon_jp",
    regionId: "jp",
    name: "Mastodon JP Signals",
    nameEn: "Mastodon JP Signals",
    url: "https://mastodon.social",
    type: "sns" as const,
    scrapeUrl: "https://mastodon.social/api/v1/timelines/public?local=true",
    scrapeIntervalMinutes: 30,
    isActive: false,
  },
  {
    id: "mastodon_tw",
    regionId: "tw",
    name: "Mastodon TW Signals",
    nameEn: "Mastodon TW Signals",
    url: "https://mastodon.social",
    type: "sns" as const,
    scrapeUrl: "https://mastodon.social/api/v1/timelines/public?local=true",
    scrapeIntervalMinutes: 30,
    isActive: false,
  },
  {
    id: "mastodon_cn",
    regionId: "cn",
    name: "Mastodon CN Signals",
    nameEn: "Mastodon CN Signals",
    url: "https://mastodon.social",
    type: "sns" as const,
    scrapeUrl: "https://mastodon.social/api/v1/timelines/public?local=true",
    scrapeIntervalMinutes: 30,
    isActive: false,
  },
  {
    id: "mastodon_us",
    regionId: "us",
    name: "Mastodon US Signals",
    nameEn: "Mastodon US Signals",
    url: "https://mastodon.social",
    type: "sns" as const,
    scrapeUrl: "https://mastodon.social/api/v1/timelines/public?local=true",
    scrapeIntervalMinutes: 30,
    isActive: true,
  },
  {
    id: "mastodon_eu",
    regionId: "eu",
    name: "Mastodon EU Signals",
    nameEn: "Mastodon Europe Signals",
    url: "https://mastodon.social",
    type: "sns" as const,
    scrapeUrl: "https://mastodon.social/api/v1/timelines/public?local=true",
    scrapeIntervalMinutes: 30,
    isActive: true,
  },
  {
    id: "mastodon_me",
    regionId: "me",
    name: "Mastodon ME Signals",
    nameEn: "Mastodon Middle East Signals",
    url: "https://mastodon.social",
    type: "sns" as const,
    scrapeUrl: "https://mastodon.social/api/v1/timelines/public?local=true",
    scrapeIntervalMinutes: 30,
    isActive: false,
  },
  {
    id: "mastodon_ru",
    regionId: "ru",
    name: "Mastodon RU Signals",
    nameEn: "Mastodon Russia Signals",
    url: "https://mastodon.social",
    type: "sns" as const,
    scrapeUrl: "https://mastodon.social/api/v1/timelines/public?local=true",
    scrapeIntervalMinutes: 30,
    isActive: false,
  },
] as const;

const CURRENT_REGION_ID_SET = new Set(REGIONS.map((region) => region.id));

export const SOURCES = [
  ...CORE_SOURCES,
  ...NEWS_SOURCES.filter((source) => CURRENT_REGION_ID_SET.has(source.regionId as (typeof REGIONS)[number]["id"])),
] as const;

export type RegionId = (typeof REGIONS)[number]["id"];
export type SourceId = (typeof SOURCES)[number]["id"];

// Cost-control policy: keep high-friction sources disabled by default.
// They can still be run explicitly via --source <id> for ad-hoc diagnostics.
export const DISABLED_SOURCE_ID_SET = new Set<string>([
]);


